repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: ruff
    entry: ruff
    types: [python]
    language: system
  - id: black
    entry: black
    types: [python]
    language: system
